### ISSUE TITLE
Can't connect to MySQL via local socket

### ISSUE THREAD

**Issue by bobcolner** [puckel/docker-airflow#10]
Hi, great progress on packaging airflow as containers, thanks!

After pulling and building the latest version of the docker images I'm still not able to access the data-profiling features. For ad-hoc queries and charts I'm getting this error:

(2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")

![screen shot 2015-11-13 at 12 45 25 pm](https://cloud.githubusercontent.com/assets/959946/11157112/8911e136-8a04-11e5-9e93-4c0a2243dac5.png)

Any advise?

**Comment by puckel** [comment]
Hi,

Two things :
- Go to Admin -> Connections and Edit "mysql_default" set this values :
* host : mysql
* Schema : airflow
* Login : airflow
* Password : airflow

Then Save and continue.

- Go back to Ad Hoc Query, select "mysql_default" in the list and run your query.

**Comment by diraol** [comment]
Just to point out here for other users, this may be fixed by these two commits:

https://github.com/puckel/docker-airflow/commit/a7ab312553d126915a93321ac813fdfde62862f1

https://github.com/puckel/docker-airflow/pull/153/commits/7872cf19b95742a0c15808e0031446a221bb17a6
