### ISSUE TITLE
Where do I define my custom python packages?

### ISSUE THREAD

**Issue by gghez** [puckel/docker-airflow#101]
I have some custom python package required by PythonOperator defined in dags. How can I import them?

**Comment by puckel** [comment]
Can you explain what you mean by import them ? 

You can install additional package (check the readme) and then you can import them the python way
```import redis``` for example.

**Comment by sdikby** [comment]
@gghez if you mean custom python that you have written yourself, you can put them in a `volume `specified in your *.yml file and then import them this way.
```
import sys
sys.path.insert(0, 'path/to/your/py_module')

import py_module
```

**Comment by gghez** [comment]
@sdikby @puckel I see ./requirements.txt take into account in entrypoint.sh script. And for my custom modules (I wrote myself) I moved it to dags sub folders in order to use it.

**Comment by NightFantomJ2** [comment]
@gghez did your requirements.txt work as-is? mine gives following logs in the worker (using docker swarm with a slightly modified celeryexecutor docker-compose file:

airflow_stack_worker@vm  |   The scripts pt2to3, ptdump, ptrepack and pttree are installed in '/usr/local/airflow/.local/bin' which is not on PATH.
airflow_stack_worker@vm  |   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

So I'm removing the --user arg in entrypoint.sh, but I'm wondering if it's only me (and then maybe related to using swarm?) or global.

**Comment by GSManganneau** [comment]
Hello @gghez 
to solve this you can add your airflow_home in your PYTHONPATH variable.
You can do this in your Dockerfile directly
`ENV PYTHONPATH "${PYTHONPATH}:${AIRFLOW_HOME}"`

**Comment by adamal** [comment]
For future stumblers like me:
In the dockerfile, AIRFLOW_HOME is not set as an ENV but as an ARG. So it is neither available if you e.g. use the puckel image as a base for something else, nor in the running container afterwards.
