### ISSUE TITLE
Getting : Error Manifest not found on airflow 1.8.1-1

### ISSUE THREAD

**Issue by emirot** [puckel/docker-airflow#106]
Doing  : 
```docker-compose -f docker-compose-CeleryExecutor.yml up```
Output : 
```
Pulling flower (puckel/docker-airflow:1.8.1-1)...
ERROR: manifest for puckel/docker-airflow:1.8.1-1 not found
```
It works fine replacing by 1.8.1 or 1.8.0

**Comment by puckel** [comment]
1.8.1-1 release builded : https://hub.docker.com/r/puckel/docker-airflow/tags/
