### ISSUE TITLE
SequentialExecutor

### ISSUE THREAD

**Issue by deepv1** [puckel/docker-airflow#128]
Is it deliberate that the entrypoint.sh doesn't start the scheduler for SequentialExecutor?

**Comment by joshuasheppard** [comment]
Looks like the `config/airflow.cfg` references the CeleryExecutor instead of the SequentialExecutor like the README describes.

`executor = CeleryExecutor`

**Comment by hbnordin2** [comment]
Any ideas on how to fix this?

**Comment by puckel** [comment]
Fixed in 1.9.0-3
