### ISSUE TITLE
root password?

### ISSUE THREAD

**Issue by david1983** [puckel/docker-airflow#135]

**Comment by ashb** [comment]
There isn't a password for any of the users in the container -- there generally isn't in docker containers.

`docker exec -u root -ti my_airflow_container bash` to get a root shell inside a running container, or `docker run --rm -ti -u root --entrypoint bash puckel/airflow` to start a new container as root.

**Comment by Pana-Onnti** [comment]
crack de la bolsa

**Comment by HenriqueOtsuka** [comment]
> There isn't a password for any of the users in the container -- there generally isn't in docker containers.
> 
> `docker exec -u root -ti my_airflow_container bash` to get a root shell inside a running container, or `docker run --rm -ti -u root --entrypoint bash puckel/airflow` to start a new container as root.

Show, it worked. Thanks
