### ISSUE TITLE
Connection issue with Redshift on COPY command

### ISSUE THREAD

**Issue by drapadubok** [puckel/docker-airflow#151]
Hi, and thank you a lot for the work here, it already helped me way more than I could have expected.

We are using docker-airflow image to setup workers, and one of the things our ETL does is perform a COPY command to put some processed data from s3 to Redshift. 
I adjusted the image to be able to use psql, and I verified that connection works. I can connect to worker container, from there connect to Redshift and run various queries. I also verified that COPY command itself works - I can successfully copy reasonably small amount of data at once.

But the main goal is to be able to copy massive chunk of data using manifest, and normally that could take a few minutes. I noticed that every time I try it, after 10-20 seconds I get:
```
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Succeeded.
```
I googled and it seems that this is related to connection timeout. I tried following https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-firewall-guidance.html#change-tcpip-settings and set those settings via docker-compose, and verified that those are in the /sbin/sysctl -a, but this doesn't help either. 

If you have any hints of what could be tried - I would be happy to try them out.

**Comment by drapadubok** [comment]
Version of docker issue, details: https://stackoverflow.com/questions/48496689/copy-from-s3-to-redshift-in-docker-container-timeout

**Comment by galliraf** [comment]
I upgraded to the latest stable docker version (19.03.1) and I still have the same issue.
