### ISSUE TITLE
/entrypoint.sh: line 99: exec: --: invalid option

### ISSUE THREAD

**Issue by romanovsky** [puckel/docker-airflow#167]
I tried to run the latest puckel/docker-airflow and faced the following issue:
```
% docker pull puckel/docker-airflow:latest
latest: Pulling from puckel/docker-airflow
Digest: sha256:a5440b75ad8cd3a862925e4e1c525c31cb53b0264d734cc70b86abad6200542f
Status: Image is up to date for puckel/docker-airflow:latest
% docker run puckel/docker-airflow:latest --name airflow
/entrypoint.sh: line 99: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```
The problem is reproduced with versions >1.9 (1.8.2 works fine)

**Comment by puckel** [comment]
Hi,

You try to run a docker run option after the image name. I invite you to check the documentation :

% docker run --help                                                                                                                                                                                     
Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
