### ISSUE TITLE
I am trying to schedule my Airflow DAG to run each Tuesday 6:00 AM,  I can do it 6:00 AM daily but how to provide 2 parameters for schedule

### ISSUE THREAD

**Issue by Satyakamrai** [puckel/docker-airflow#177]
Just to add additional information, I have set schedule_interval as '0 6 * * 2' in DAG script

**Comment by johnlovesdata** [comment]
Could you provide more details on the issue you're having? Is the job not running at all? Running at an unexpected time?

**Comment by Satyakamrai** [comment]
issue resolved, when set time, next day it picks correct time
