### ISSUE TITLE
container not running 

### ISSUE THREAD

**Issue by ZaneH1992** [puckel/docker-airflow#183]
When i pulled the latest image from dock hub and run it, it seems the contain starts and makes immediate exit with status 0. 
![image](https://user-images.githubusercontent.com/38309495/39853198-5007ccf4-5453-11e8-8dcb-0d9414c043f9.png)
![1](https://user-images.githubusercontent.com/38309495/39853258-b74b8eaa-5453-11e8-905a-bc3f2886fd90.png)

Did i do something wrong?

**Comment by richardkippers** [comment]
The same problem occurred at my machine, but when using compose (https://github.com/puckel/docker-airflow/blob/master/docker-compose-LocalExecutor.yml) everything works just fine.

**Comment by puckel** [comment]
@ZaneH1992 Fixed in the last release 1.9.0-3

**Comment by timttate** [comment]
I think I'm seeing the same behavior with the 1.9.0-3 release.

After running the command:
`docker run -d -p 8080:8080 puckel/docker-airflow:1.9.0-3`

I get the following output from docker ps:
`cdeacf147508        puckel/docker-airflow:1.9.0-3                         "/entrypoint.sh"         3 seconds ago        Exited (0) 3 seconds ago                                 fervent_ritchie`

**Comment by puckel** [comment]
Hi @timttate 

It's the default behavior if you pass nothing [entrypoint.sh#L90](https://github.com/puckel/docker-airflow/blob/9f00550be9f3365215e2412419544a8301752fdd/script/entrypoint.sh#L90)

If you want to simply run Airflow in standalone mode (SequentialExecutor) :

`docker run -d -p 8080:8080 puckel/docker-airflow:1.9.0-3 webserver`

**Comment by timttate** [comment]
Ahhh, I see now. Thank you.
