### ISSUE TITLE
libmysqlclient-dev

### ISSUE THREAD

**Issue by pnats** [puckel/docker-airflow#187]
This is a stopping point always. ubuntu 14 or 16

E: Package 'libmysqlclient-dev' has no installation candidate

**Comment by achm6174** [comment]
I also face the same issue when I rebuilt my image recently. Below is my solution and hope it works for you:

In your docker file, change line 46 from 

        libmysqlclient-dev \

to

        default-libmysqlclient-dev  \

A possible reason is image python:3.6-slim recently upgraded from Debian 8 (Jessie) to Debian 9 (stretch), so some of the packages in newer version cannot be found.
Details: https://github.com/brianmario/mysql2/issues/964

**Comment by pnats** [comment]
Odd. I am using the default ami Ubuntu from AWS as a build server. I have been using your master branch for 2 weeks with no problem. I decided to clean and start over after some testing. Building a new server ami for build this thing started to download the mariadb ? instead of the normal mysql.
I just happened to look up and the logging was flying by. I put in the package name as libmariadbclient-dev and all works as it should. Odd this was working without issue, all generic command line and now it switched. Perhaps it was something I did.

I install ami Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-6a003c0f

install docker per the page: https://docs.docker.com/install/linux/docker-ce/ubuntu/
Test hello world docker image

Install your master:

git clone https://github.com/puckel/docker-airflow.git

sudo docker build -t airflow .

The above worked last couple of weeks out of the box. Now the ubuntu is grabbing mariadb instead of I guess the normal one.

Not that I care to much on the client stuff as long and it can connect to a RDS mysql but any thoughts on this ?

**Comment by fournierinfusion** [comment]
Made the change above and the docker container is exiting after run. It intially was failing to build before the change but after it builds but just exits instead of persisting with docker build -d -p 8080:8080 <>

**Comment by Rohan9969** [comment]
I replaced "FROM python:3.6-slim" with "FROM python:3.6-slim-jessie". 

The docker image was created successfully with above change but while running the airflow instance I faced an error "AttributeError: async" which resolved by upgrading celery to 4.1.1

**Comment by puckel** [comment]
Fixed in 1.9.0-4
