### ISSUE TITLE
Dockerfile build conflicts with pgdata volume

### ISSUE THREAD

**Issue by tiagovrtr** [puckel/docker-airflow#211]
I have been using the Celery docker-compose setup and I have set pgdata for persistent storage of the metadata DB. Now if I try to rebuild the Dockerfile, I get this

> `[tiago@host docker-airflow]$ docker build .`
>  `error checking context: 'can't stat '/home/tiago/docker-airflow/pgdata''.`

If I try to build from a path above I get the same

> `[tiago@host ~]$ docker build .`
>  `error checking context: 'can't stat '/home/tiago/docker-airflow/pgdata''.`

It potentially has to do with the permissions for the pgdata directoy

> `[tiago@host docker-airflow]$ ls -la`
> `total 88`
> `drwxr-xr-x.  9 tiago   devs  4096 Aug  3 10:12 .`
> `drwx------. 10 tiago   devs  4096 Aug  3 10:14 ..`
> `-rw-r--r--.  1 tiago   devs   320 Aug  1 16:20 circle.yml`
> `drwxr-xr-x.  2 tiago   devs  4096 Aug  3 10:10 config`
> `drwxr-xr-x.  2 tiago   devs  4096 Aug  3 09:05 dags`
> `-rw-r--r--.  1 tiago   devs  2855 Aug  1 16:20 docker-compose-CeleryExecutor.yml`
> `-rw-r--r--.  1 tiago   devs   811 Aug  1 16:20 docker-compose-LocalExecutor.yml`
> `-rw-r--r--.  1 tiago   devs  2564 Aug  3 09:47 docker-compose.yml`
> `-rw-r--r--.  1 tiago   devs  2315 Aug  2 13:10 Dockerfile`
> `-rw-r--r--.  1 tiago   devs     5 Aug  1 16:20 .dockerignore`
> `drwxr-xr-x.  8 tiago   devs  4096 Aug  2 17:19 .git`
> `-rw-r--r--.  1 tiago   devs   475 Aug  1 16:20 .gitignore`
> `-rw-r--r--.  1 tiago   devs 11355 Aug  1 16:20 LICENSE`
> `drwxr-xr-x.  2 root    root  4096 Aug  2 17:23 logs`
> `**drwx------. 19 polkitd root  4096 Aug  3 10:12 pgdata**`

Is there a way to rebuild the image without having to sudo rm this directory?

**Comment by ena1106** [comment]
Same problem here. Did you find the solution?

**Comment by KimchaC** [comment]
I've been able to solve this by adding my volumes folder (which contains pgdata) to my .dockerignore:
```
$ cat .dockerignore 
volumes/
```

**Comment by tiagovrtr** [comment]
That's a good solution Kimcha. So the issue is that the volumes are being created on build time using a different user inside the container (hence the funny polkitd user). A better solution that makes sure you keep permissions to the directories bound as volumes is to create them beforehand so that they keep the host user's ownership.

**Comment by KimchaC** [comment]
I think I've tried doing chown -R airflow:airflow pgdata, but the permissions were reset after the container was restarted. So excluding it from the build process was the only option that worked for me.
