### ISSUE TITLE
1.10.0 was released

### ISSUE THREAD

**Issue by victornoel** [puckel/docker-airflow#219]
Is there a timeline on when the image will be updated?

Thanks!

**Comment by enys** [comment]
It looks like the pypi package has not been released yet.
I'm currently using this image with an extra layer with airflow pip
installed from GitHub tag.

Le ven. 24 août 2018 à 17:44, Victor Noël <notifications@github.com> a
écrit :

**Comment by puckel** [comment]
Following the Airflow release from Python Package Index

**Comment by victornoel** [comment]
@puckel could have been nice to keep this open until the new version is merged in master, so that we can follow the matter from this issue :)
