### ISSUE TITLE
DAGs not clickable on Webserver

### ISSUE THREAD

**Issue by y2k-shubham** [puckel/docker-airflow#236]
I'm trying to run `docker-airflow` using `CeleryExecutor` on `EMR` (all docker commands must be prefixed with `sudo`). As [suggested by **@mhousley**](https://github.com/puckel/docker-airflow/issues/107#issuecomment-336680976) I've mounted a persistent volume for `PostgreSQL`.

After doing `sudo docker-compose -f docker-compose-CeleryExecutor.yml up -d` and creating all connections and variables from _WebUI_, I still don't see my `DAG`s in _WebUI_. So I do `sudo docker exec -it docker-airflow_scheduler_1 bash` and check the _error logs_ to find that it throws `error: no such table: log`.

To overcome it, I perform `airflow initdb` (from within the _scheduler container_) as [told by **@kifjj**](https://github.com/puckel/docker-airflow/issues/230#issuecomment-420053933). This gives a stacktrace ending in `KeyError: 'Variable <variable-name> does not exist'`.

From here [I have no clue](https://github.com/puckel/docker-airflow/issues/230#issuecomment-422036994) what to do. I'm not even sure where should I invoke `airflow initdb` command.

**Comment by y2k-shubham** [comment]
I must add that every time I do `sudo docker-compose -f docker-compose-CeleryExecutor.yml up -d`, the ownership of `pgdata` directory (that I've mounted for `PostgreSQL`) goes to user `999` and I have to manually change it back to `hadoop` user. But even doing that has no impact.

**Comment by y2k-shubham** [comment]
I've managed to replicate the issue on my `Mac` so it definitely isn't isolated to `EMR` (or `sudo docker..` messing up permissions as I earlier thought). Manually querying `postgres` I can confirm that `Variable`(s) and `Connection`(s) that I created via WebUI have persisted in db. I'm currently looking along the lines of `Airflow` user

**Comment by y2k-shubham** [comment]
Mounting **PIP**'s `requirements.txt` file into **webserver** _container_ (in `docker-compose`) did the trick. At the time of writing, my `requirements.txt` had following dependencies
```
boto3===1.8.4
paramiko===2.4.1
```

**Comment by gfelot** [comment]
@y2k-shubham did you mount the requirements file to the root of your container ? Can you share your docker-compose ?

**Comment by musa-atlihan** [comment]
@gfelot 

add `requirements.txt` in the same folder with the `docker-compose-LocalExecutor.yml` file.

then mount that file to the root of the container like this:

```
...
    webserver:
...
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./requirements.txt:/requirements.txt
            # - ./plugins:/usr/local/airflow/plugins
...
```

**Comment by musa-atlihan** [comment]
adding `requirements.txt` in the same folder with the `docker-compose-LocalExecutor.yml` file.

then mounting that file to the root of the container solves this.

```
...
    webserver:
...
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./requirements.txt:/requirements.txt
            # - ./plugins:/usr/local/airflow/plugins
...
```
