### ISSUE TITLE
Sudo is required by airflow, but not available, causes crash.

### ISSUE THREAD

**Issue by jlricon** [puckel/docker-airflow#244]
The docker image will not have sudo installed as it inherits ultimately from debian:stretch-slim which has no sudo by default. Airflow will try to run commands with sudo in certain situations, e.g. when running out of memory airflow/task/task_runner/base_task_runner.py will run 
```
subprocess.call(['sudo', 'rm', self._cfg_path], close_fds=True)
```
which will result in a crash as sudo is not available.

Fix is to apt-get install sudo by default and add the airflow user  to the sudoers group.

**Comment by rmarathay** [comment]
Try entering the docker container as root using `sudo docker exec -u 0 -it <container_id> /bin/bash` and change permissions for users or files manually.

**Comment by jlricon** [comment]
Sure, I know how to fix it manually. In my own docker image I used the fix outlined in my issue. What I'm proposing is that this fix is included in the image itself because upstream airflow needs sudo. It is as if this image were shipping without, say, flask installed.

**Comment by ashb** [comment]
This is a bug in airflow which should be fixed there (`sudo` should only be required when impersonation is used, which it isn't by default)

**Comment by polinabee** [comment]
Has this been updated, is sudo required for the airflow user? It seems to still be the case
