### ISSUE TITLE
Getting this error in docker Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"webserver\": executable file not found in $PATH": unknown.

### ISSUE THREAD

**Issue by rajib2k5** [puckel/docker-airflow#256]
I see the error below when I try to build and run this command:
```
docker run -d -p 8080:8080 puckel/docker-airflow webserver

```

Error Messsage:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"webserver\": executable file not found in $PATH": unknown.

**Comment by ststo** [comment]
Had a similar issue, see also: https://github.com/moby/moby/issues/37713
Solution for me was restarting the pc, restarting docker was not enough.

**Comment by codersky** [comment]
do you guys have any clues for this issue? i also met this.

**Comment by gabrielboehme** [comment]
Im also facing this problem. Anyone?

**Comment by PavelPopov1** [comment]
Do you have the answer? I faced this problem too.

**Comment by rajib2k5** [comment]
Stefan's idea worked for me 2 years ago... some time, rebooting the entire environment helps. These types of problems are common in most technologies. They give out error message that's just too generic and makes no sense. Rebooting a PC is like a kick to the vending machine... it'll work... if not, there is something else worth researching.
