### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: log

### ISSUE THREAD

**Issue by hackenzheng** [puckel/docker-airflow#267]
Use docker-compose cmd start airflow successfully, then docker exec  into  the webserver container.  When  use airflow command such as 'airflow list_dags', there was a error 'no such table: log', but the command output result is correct. How to solve?  I have confirmed the log table is in the postgresql

**Comment by miro-ka** [comment]
are you trying to run default SequentalExecutor? It would help if you could write here exact commands you are executing.

**Comment by hackenzheng** [comment]
I used 'docker-compose -f docker-compose-CeleryExecutor.yml up -d'  to start  airflow with Celery mode,
but the executing log shows the Executor was SequentialExecutor and the airflow.cfg was set SequentialExecutor.  Any airflow sub commands  like airflow list_dags has the error "no such talbe: log". 
Would this is related to SequentialExecutor?

**Comment by Nikhil-Hiremath** [comment]
I am also getting the same error.Please respond.

**Comment by miro-ka** [comment]
just to be 100% sure,..these are the steps, that are giving your 'SequentialExecutor,...'no such table: log'..) problem?


```
docker-compose -f docker-compose-CeleryExecutor.yml up -d'
docker-compose -f docker-compose-CeleryExecutor.yml run --rm webserver airflow list_dags
```

**Comment by hackenzheng** [comment]
yeah, it works, thanks.   It's different with executing cmds in the container.

**Comment by danrubenstein** [comment]
If you've already figured this one out, feel free to ignore, but perhaps part of the issue that when you run commands from inside the container, you're missing a lot of the environment variables that are set in the entrypoint script (like the [one to set the sql alchemy connection](https://github.com/puckel/docker-airflow/blob/master/script/entrypoint.sh#L25)). When you run exec commands, those environment variables haven't been set, so Airflow falls back on the default values for those parameters, which I believe is a [SQLite database](https://github.com/apache/incubator-airflow/blob/master/airflow/config_templates/default_airflow.cfg#L87) and the [Sequential Executor](https://github.com/apache/incubator-airflow/blob/master/airflow/config_templates/default_airflow.cfg#L82) 

As a result, if you're running from a SQLite database, which you haven't initialized with the airflow schema, you could be missing the requisite logs table, as you suggest in the next comment. I believe the reason the docker-compose files work is that those commands get run from the entrypoint, and as a result, the environment variables get set such that you run with the CeleryExecutor and the Postgres connection.

The way to get around this, I think, is to set more env vars in your container, either on create from the docker compose file or by `EXPORT`ing them after you exec in.

**Comment by hackenzheng** [comment]
yeah, I think so, thanks for analysis and suggestions

**Comment by alireza-alizadegan** [comment]
I get this error when I'm trying to get list of dags. Even though my dags are up and running in the web UI I get this error when I `list_dag` in terminal. I `initdb` in the directory that my dags are but still no result
