### ISSUE TITLE
Airflow tasks get queued and never executed on redis-py 3.0.0 

### ISSUE THREAD

**Issue by prideloki** [puckel/docker-airflow#268]
redis-py has updated new version to 3.x.x. and my Airflow tasks get queued and never executed.

See https://github.com/andymccurdy/redis-py#upgrading-from-redis-py-2x-to-30
And from Airflow https://github.com/apache/incubator-airflow/blob/v1-10-stable/setup.py#L203 it wrote `'redis>=2.10.5'`

I don't know why I fork your repo and cannot make a PR
I created a PR here https://github.com/prideloki/docker-airflow/pull/1

**Comment by bsekiewicz** [comment]
Now they have redis>=2.10.5,<3.0.0. Airflow returns such error: "Unrecoverable error: AttributeError("'float' object has no attribute 'items'",)"

You can add 'pip install redis==2.10.6' before celery[redis] installation - its temporary but quick solution.
