### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by abourget** [puckel/docker-airflow#27]
Hi.. I've been working on a Kubernetes deployment.

Is that something you'd be interested in adding in here ?

**Comment by mogthesprog** [comment]
Hey, not part of the docker airflow project but i'd love to see what you've done. We're just setting out to have a go at building our own. More than happy to collab/develop! We have a baremetal k8s instance to play with.

**Comment by mumoshu** [comment]
FYI, I have managed to create https://github.com/mumoshu/kube-airflow based on/thanks to docker-airflow.
Hope it helps!

**Comment by puckel** [comment]
Thanks. Added to links section in readme.
