### ISSUE TITLE
PythonOperator does not work

### ISSUE THREAD

**Issue by fbdiehlad** [puckel/docker-airflow#30]
I'm running into an issue where the PythonOperator just straight up fails when running airflow backfills. Even an extremely simple use case (https://gist.github.com/fbdiehlad/9e356d9a303339eb3c3f1be3475efce2) fails immediately when I try to run a backfill against it.  Oddly enough, when I run the task using airflow test, it works fine.  I'm thinking this is some kind of permissions issue from running the setup with docker?  Has anyone else run into this before?

**Comment by puckel** [comment]
Hi,

Could you provide the full execution log ?

Thanks
