### ISSUE TITLE
How to change airflow static folder root path

### ISSUE THREAD

**Issue by mabubackar** [puckel/docker-airflow#31]
Hello, 

Our current airflow static folder is residing under root path. We are looking for how to change the static root path [/static].   Is any specific configuration file using [/static]. If so, how to change it. Highly appreciated if anybody can help to sort out this issue?

**Comment by puckel** [comment]
Hi,
Did you try to change `ENV AIRFLOW_HOME /usr/local/airflow` in Dockerfile and rebuild ?

**Comment by mabubackar** [comment]
Yes. It is working with root static[/static] using nginx reverse proxy. . But, problem is we have couple other static contents need to run. So, we want to change the static path for airflow. Is any specific configuration file to change /static to /airlow/static[example]

**Comment by mabubackar** [comment]
Yes. It is working with root static[/static] using nginx reverse proxy. . But, problem is we have couple other static contents need to run. So, we want to change the static root path for airflow. Is any specific configuration file to change /static to /airlow/static[example]

**Comment by puckel** [comment]
I don't understand what do you want. You want to have airflow binary in /airflow/static or the configuration and dags folder ?

**Comment by mabubackar** [comment]
we are trying to do a nginx reverse proxy to airflow, but due to the multi mix of docker apps, we are ending up by requiring proxy URL to  /static (for css , html, and js files). So in airflow, we intend to add a suffix url to /static files,  so that it can be uniquely identified by nginx for example http://example.com/airflow/static.

**Comment by puckel** [comment]
sorry but it's not an issue/question linked to docker-airflow. Try to ask directly to the airflow mailing-list. Thanks

**Comment by harryprince** [comment]
@mabubackar I meet the same problem, how do you solve that?

**Comment by dshakey** [comment]
> @mabubackar I meet the same problem, how do you solve that?

did you ever get this working?
