### ISSUE TITLE
Anaconda environments inside containers so we can use BashOperator to run scripts in different python versions

### ISSUE THREAD

**Issue by bryan3189** [puckel/docker-airflow#321]
Has anybody installed Anaconda environments inside airflowdocker containers so we can use BashOperator to run scripts in different python versions

**Comment by zhongjiajie** [comment]
@bryan3189 You could do it buy yourself, maybe just change base images to Anaconda? (not sure about that becasuse I don not use it)

**Comment by bryan3189** [comment]
Got it. Thanks @zhongjiajie 

I made use of something similar to add anaconda to the image:
https://hub.docker.com/r/continuumio/anaconda3/dockerfile
