### ISSUE TITLE
Wrong executor

### ISSUE THREAD

**Issue by sbatururimi** [puckel/docker-airflow#325]
I started my containers with 

`docker-compose -f docker-compose-LocalExecutor.yml up -d`

but instead, the local executor, the sequential one is still used:

> airflow webserver -p
> [2019-03-07 16:41:49,636] {{__init__.py:51}} INFO - Using executor SequentialExecutor

as well as airflow.cfg is not updated with the  **EXECUTOR** environment variable specified in  docker-compose-LocalExecutor.yml file

**Comment by sbatururimi** [comment]
Have found the solution here https://github.com/puckel/docker-airflow/issues/318

**Comment by aljanson** [comment]
I have the same problem, and I am still confused about this. In the docker compose file we do use the puckel/docker-airflow:latest image, so shouldn't that already be built with the entrypoint.sh file?

I mean the link you have provided, only applies to when you try to do things manually within the container.
