### ISSUE TITLE
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-LocalExecutor.yml'

### ISSUE THREAD

**Issue by pratikhonrao** [puckel/docker-airflow#337]
Hello, I am totally new to airflow and have been following your steps to learn more on DAGS before creating a one for myself, I have done the initial setup and on UI when I turn ON the DAG's files and begin execution (trigger) the program enters running mode but it goes on indefinitely never stops. 
Unable to see the task progressing as well. 

![image](https://user-images.githubusercontent.com/47742886/55248137-13336d00-5241-11e9-9d65-35351112fc14.png)

In my investigation I found this: 

To run any DAGs, you need to make sure two processes are running:
1.airflow webserver
2.airflow scheduler

so I guess I do not have a scheduler running so I ran -- 

`docker-compose -f docker-compose-LocalExecutor.yml up -d`  
AND 
`docker-compose -f docker-compose-CeleryExecutor.yml up -d`

However I am getting below error: 

`ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-CeleryExecutor.yml'`

`ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-LocalExecutor.yml'`

Does anybody know how do I resolve this?  I have docker-compose installed. 

`docker-compose --version`
`docker-compose version 1.22.0, build f46880fe`

**Comment by ls12styler** [comment]
@pratikhonrao I know this is going to sound silly, but are you running the `docker-compose` command in the same directory you cloned the repository into?

**Comment by pratikhonrao** [comment]
@ls12styler 

Hi Ashley, 

Issue resolved. I did not had LocalExecutor.yml file and was trying to run docker-compose -f docker-compose-LocalExecutor.yml up -d. Silly me. 
Solution was to simply create clone that file into your directory where you are trying to run  docker-compose -f docker-compose-LocalExecutor.yml up -d. 

Issue resolved. Closing. Thanks for your help !
