### ISSUE TITLE
dags tab is empty

### ISSUE THREAD

**Issue by steffmul** [puckel/docker-airflow#352]
I am new to airflow and struggle to see the dags from my host folder (local windows 10 laptop) in the dags tab. I am using this command: 
docker-compose -f docker-compose-CeleryExecutor.yml up -d
and it launches airflow under [mydockerIP]:8080

do I have to add anything or open ports?
Is the local folder properly mapped? 

when I run:
docker run -d -p 8080:8080 -v /C/docker-airflow/dags://usr/local/airflow/dags  puckel/docker-airflow webserver
 
I get this output: 
3d81d2d2a4f48a42197b36beaca23ece750cdeb6d638ba7aa3b0c7abb26f655f
C:\Program Files\DockerToolbox\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint sad_morse (853604e79af6cfc0466f3d2214599da37d10e18589ad1731a6a1bf28ade801df): Bind for 0.0.0.0:8080 failed: port is already allocated.

any help is welcome. 

![bash](https://user-images.githubusercontent.com/28976430/56033200-49ceb480-5d24-11e9-9b7a-48b54063b35b.png)
![dag folder 2 files](https://user-images.githubusercontent.com/28976430/56033201-4a674b00-5d24-11e9-8de1-c3339b65ba2d.png)
![dags](https://user-images.githubusercontent.com/28976430/56033202-4a674b00-5d24-11e9-9b88-802c3bffc9ab.png)
![folders](https://user-images.githubusercontent.com/28976430/56033203-4a674b00-5d24-11e9-9f87-1faf67698c17.png)

**Comment by steffmul** [comment]
yml file as txt
[docker-compose-CeleryExecutor.txt](https://github.com/puckel/docker-airflow/files/3073264/docker-compose-CeleryExecutor.txt)

**Comment by siddardha7** [comment]
Bring down the running container before starting a new container with same port allocation.
Port 8080 is already allocated, so the next time you run the a different docker-compose file and request for the port 8080, it will error out. 

Either change the port to something else or stop the existing. 

To stop the running

**docker-compose -f docker-compose-CeleryExecutor.yml down**

If you have something else running on 8080, just edit this line in the docker compose file.

-8080:8080  
give it like -8088:8080

Now your webserver will be running on port 8088.

**Comment by is2co** [comment]
You need to make sure that the previous container you launched is killed, before launching a new one that uses the same port:

docker container ls -a
docker rm -f <container-name>

**Comment by steffmul** [comment]
thanks I got it resolved. Indeed I needed to kill it first.
