### ISSUE TITLE
LOAD_EX in multiple services

### ISSUE THREAD

**Issue by kachkaev** [puckel/docker-airflow#37]
Hi @puckel,

I just noticed that it is suggested to uncomment `LOAD_EX=n` in two services both inside `docker-compose-CeleryExecutor.yml` and `docker-compose-LocalExecutor.yml`. Is it how it is supposed to be? I'd intuitively expect this ENV variable to be needed only once because I don't think that more than one service can be responsible for adding extra DAGs. How about removing an extra occurrence of  `LOAD_EX=n` if not needed?

Thanks a lot for crafting the docker recipe for airflow - sooo cool to be able to launch airflow in under a minute without any preps!

**Comment by puckel** [comment]
Hi,

I've tried both options, the dags examples are loaded when the option is activated in webserver or scheduler
