### ISSUE TITLE
LocalExecutor not executing tasks

### ISSUE THREAD

**Issue by AxelFurlanF** [puckel/docker-airflow#371]
I've been using `SequentialExecutor` but I want to switch to `LocalExecutor` since the former is non-viable for dags that can advantage from parallelism.
I'm not using docker-compose. I've got my own RDS postgres instance and all `POSTGRES_` environment variables configured to use it.
Running the container seems to use the correct executor but all tasks are being `queued` and never start `running` state.

By detaching the container run from my terminal, I can see the following traceback error:
```
[2019-05-23 18:31:47,509] {{jobs.py:1341}} INFO - Sending ('push_data_RDS', 'latest_only', datetime.datetime(2019, 5, 22, 0, 0, tzinfo=<TimezoneInfo [UTC, GMT, +00:00:00, STD]>), 1) to executor with priority 7 and queue default
[2019-05-23 18:31:47,510] {{base_executor.py:56}} INFO - Adding to queue: airflow run push_data_RDS latest_only 2019-05-22T00:00:00+00:00 --local -sd /usr/local/airflow/dags/push_data_RDS.py
Process QueuedLocalWorker-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/site-packages/airflow/executors/local_executor.py", line 113, in run
    key, command = self.task_queue.get()
  File "/usr/local/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
TypeError: __init__() missing 5 required positional arguments: 'tz', 'utc_offset', 'is_dst', 'dst', and 'abbrev'
```
Doesn't seem to be the image's error but an airflow/python one.
Couldn't find the solution for this and others don't seem to be experiencing this issue.

Would appreciate any help.

**Comment by darkn3rd** [comment]
Can you access RDS from the host or from within the container? 

What is the `sql_alchemy_conn` configuration?
```
docker exec -ti $(docker ps -f name=airflow -q) grep sql_alchemy_conn airflow.cfg
```

**Comment by darkn3rd** [comment]
Actually, update, it looks like airflow.cfg is not configured.  You can check the if the variables are valid for the current executing process

```
docker exec -ti -u root $(docker ps -f name=airflow -q) sh
tr '\0' '\n' < /proc/1/environ | grep AIRFLOW__CORE
```
You should see that `AIRFLOW__CORE__EXECUTOR=LocalExecutor` and that `AIRFLOW__CORE__SQL_ALCHEMY_CONN` is set to your RDS endpoint.

**Comment by AxelFurlanF** [comment]
Thanks for the responses! As you said, my RDS instance is publicly accessible by all IPs. It actually is being used by the sequential executor right now so no problema with that. Problem arises when I switch to Local one using the env var that you mentioned, I double checked in airflow.cfg if the Executor was set properly and it was.

**Comment by AxelFurlanF** [comment]
I’ll paste my sqla configuration in a bit.

**Comment by darkn3rd** [comment]
I assume you created the user, database, (and if schema if postgres).  I am currently testing locally on my own setup with Vagrant + Docker Compose, and it seems to work.  I will shortly test this on RDS.

```yaml
version: '2.1'
services:
    webserver:
        image: puckel/docker-airflow:1.10.3
        restart: always
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=REDACTED
            - POSTGRES_DB=airflow
            - POSTGRES_HOST=192.168.53.75
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
```

**Comment by AxelFurlanF** [comment]
I remember seeing in the logs every time the `airflow scheduler` that `LocalExecutor` was being used. Nevertheless, I've never set `LOAD_EX=n` as you did in the compose file, what's the purpose of that env?

**Comment by AxelFurlanF** [comment]
Solved by meeting the pip requirements correctly (using the correct version).

**Comment by benjtlv** [comment]
> Solved by meeting the pip requirements correctly (using the correct version).

Can you elaborate a little bit on this please ?

**Comment by AxelFurlanF** [comment]
> > Solved by meeting the pip requirements correctly (using the correct version).
> 
> Can you elaborate a little bit on this please?

I can yes. I had my own docker image inheriting from puckel's. The entrypoint executes the `pip install requirements.txt`, but my requirements had versions conflicting with other airflow dependencies, so I just looked at the airflow log to check which were those conflicting dependencies and just met them with their correct version suggestion.
An example of a requirement not met:
```
ERROR: flower 0.9.3 has requirement tornado<6.0.0,>=4.2.0, but you'll have tornado 6.0.2 which is incompatible.
```
As I don't use flower I don't care, but other tools such as `werkzeug` I think are being used by airflow's scheduler, so that would probably screw up with task management.
