### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by gfelot** [puckel/docker-airflow#404]
I need to add boto3 to my project so I wanted to build my own image. Unfortunately even the original Dockerfile fail on my machine:

```
Step 16/23 : COPY script/entrypoint.sh /entrypoint.sh
COPY failed: stat /var/lib/docker/tmp/docker-builder103105278/script/entrypoint.sh: no such file or directory
```

And now a simple `docker run...` gives me this error:

```
Unable to find image 'airflow:latest' locally
docker: Error response from daemon: pull access denied for airflow, repository does not exist or may require 'docker login'.
```

Even if I had remove the image and pull it again.

**Comment by sphimmer** [comment]
did you find a solution? if so could you share it?
