### ISSUE TITLE
How to install custom pip packages?

### ISSUE THREAD

**Issue by michael-erasmus** [puckel/docker-airflow#41]
Curious if there is any way control installing custom pip packages? I was hoping that you could perhaps use something like the `ONBUILD` triggers on the [Python image](https://hub.docker.com/_/python/)

To be more specific why I'm asking is that I tried using the `DockerOperator` in a DAG and I'm running into the following error: ` No module named docker` 

My guess is that we need to install the `docker` package.

**Comment by puckel** [comment]
I'm on it.

**Comment by puckel** [comment]
With the ONBUILD command, you have to rebuild the image (too long), so I added the package installation into the entrypoint script by passing a `requirements.txt` (as a volume).

**Comment by michael-erasmus** [comment]
Wow, this is awesome! Thanks so much @puckel, trying it out right now, will let you know how it works out!

**Comment by apurvis** [comment]
i am trying to build a child image using `FROM puckel/docker-airflow:latest`... having `ONBUILD` options would be kind of awesome, because i can't pass build args like `AIRFLOW_DEPS` via `FROM`...
