### ISSUE TITLE
Not able to see airflow logs in ui

### ISSUE THREAD

**Issue by Dcubeanalytics** [puckel/docker-airflow#413]
Hi,

my airflow logs not showing in web ui. below error is i am getting by using CeleryExecutor, could any  one help please.

*** Log file does not exist: /usr/local/airflow/logs/ecs-test/Get_Dyanamic_py_File/2019-08-01T11:18:15.045274+00:00/1.log
*** Fetching from: http://9b6bdf24613a:8793/log/ecs-test/Get_Dyanamic_py_File/2019-08-01T11:18:15.045274+00:00/1.log
*** Failed to fetch log file from worker. HTTPConnectionPool(host='9b6bdf24613a', port=8793): Max retries exceeded with url: /log/ecs-test/Get_Dyanamic_py_File/2019-08-01T11:18:15.045274+00:00/1.log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1cdeb73a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by zachliu** [comment]
@Dcubeanalytics How did you solve it? I have the same issue.

**Comment by swapniel99** [comment]
The host 9b6bdf24613a is actually the containerID of worker.
If container is replaced the containerID will change. Also since logs were local, they cannot be recovered.

**Comment by sameer-subudhi** [comment]
@swapniel99 I am facing the same issue
Could you please provide the solution for this or any other workaround ?

**Comment by swapniel99** [comment]
@sameer-subudhi In airflow config, use s3 for saving logs.
