### ISSUE TITLE
[Errno 2] No such file or directory: './docker-compose-LocalExecutor.yml'

### ISSUE THREAD

**Issue by JavierLopezT** [puckel/docker-airflow#415]
Hello, I have tried to execute Airflow with the LocalExecutor with the following command:
`docker-compose -f docker-compose-LocalExecutor.yml up -d`

And I have received the error which is stated in the title. I have tried to find the file using `locate` and` find` with no success. For installing it I have just used 
`docker pull puckel/docker-airflow`

And if I run it directly with the sequential executor it works. I have thought that it might be related with the fact that I have not used the build command, so I have made:
`docker build --rm --build-arg AIRFLOW_DEPS="datadog,dask" -t puckel/docker-airflow .`

Which throws me the following error:
`unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/ubuntu/Dockerfile: no such file or directory`

I have no idea if both errors are related but anyway, I am unable to execute Airflow with LocalExecutor. Could you help me please? 

Thank you very much

**Comment by enys** [comment]
Hi,
I'm guessing you could be new to the docker environment ?

The files are available in this repository. You will need to git clone this repo, and run commands from there.

**Comment by JavierLopezT** [comment]
Yes, it was that.  Thank you very much!

**Comment by enys** [comment]
Great !
Perhaps you could close the issue ?

**Comment by JavierLopezT** [comment]
closes
