### ISSUE TITLE
Geopandas dependence of libspatialindex

### ISSUE THREAD

**Issue by RCCSilva** [puckel/docker-airflow#427]
Hello, I'm trying to install `geopandas` with the requirements.txt file using the docker-compose ( `docker-compose-LocalExecutor.yml`). But since it depends on libstapialindex, it is not working. Is there a working approach for this or I'd have to edit the Dockerfile and install the libstapialindex in my image?

**Comment by zenweasel** [comment]
I believe the only way to do this is to fork the dockerfile and add any binary dependencies

**Comment by ab-w** [comment]
@zenweasel One doesn't need to "fork" or "edit" the preexisting Dockerfile. That would probably be an antipattern for Dockerfiles. Rather, `puckel/docker-airflow` can be used as a base image in a new Dockerfile.

Here is an example of a minimal derived Dockerfile:

```Dockerfile
FROM puckel/docker-airflow:1.10.4

# Apply relevant subset of https://github.com/puckel/docker-airflow/pull/359/files for airflow scheduler to run:
USER root
RUN sed -i 's/LocalExecutor/SequentialExecutor/' /entrypoint.sh
USER airflow

HEALTHCHECK CMD "[ -f /usr/local/airflow/airflow-webserver.pid ]"
```

**Comment by ab-w** [comment]
@RCCSilva As an aside, I highly recommend decoupling the actual jobs from the Airflow installation. The actual jobs can be independent Docker images, for example.
