### ISSUE TITLE
Docker for Airflow 1.10.5

### ISSUE THREAD

**Issue by mikonapoli** [puckel/docker-airflow#435]
Not a major, but can we have an updated version? This release fixes several bugs in a few operators...

**Comment by TylerBrock** [comment]
Yup, let's do it, would love to run 1.10.5

**Comment by zachliu** [comment]
Just change the version in `Dockerfile` 
```
ARG AIRFLOW_VERSION=1.10.5
```
and add
```
&& pip install 'Flask==1.1.0' \
```
after
```
&& pip install 'redis==3.2' \
```
although I don't remember why :man_facepalming:

**Comment by Lord-Y** [comment]
@zachliu maybe you should do a PR :)

**Comment by zachliu** [comment]
@Lord-Y totally forgot my duty to the opensource community :man_facepalming:, I'll do it milord

**Comment by Ellmen** [comment]
I know we have support for 1.10.6 but I would still like 1.10.5. 1.10.6 seems to have introduced some bugs with scheduling large DAGs.
