### ISSUE TITLE
Flower Crashing

### ISSUE THREAD

**Issue by stobias123** [puckel/docker-airflow#46]
I'm borrowing a lot from your docker compose to deploy in an openshift environment and the Flower pod crashes consistently with the following error...
```
Traceback (most recent call last):
  File "/usr/local/bin/flower", line 11, in <module>
    load_entry_point('flower==0.9.1', 'console_scripts', 'flower')()
  File "/usr/local/lib/python2.7/dist-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flower/command.py", line 59, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/usr/local/lib/python2.7/dist-packages/flower/command.py", line 36, in run_from_argv
    self.apply_env_options()
  File "/usr/local/lib/python2.7/dist-packages/flower/command.py", line 71, in apply_env_options
    value = option.type(value)
ValueError: invalid literal for int() with base 10: 'tcp://172.30.195.95:5555'
```

I think this is due to the fact that the pod is trying to access celery via IP rather than service name. The flower pod works fine and actually connects to `http://localhost:5555`  when I import the service from using the `kube-airflow` project. I'm having trouble finding where the IP address is passed into the Flower pod so I can change it from IP to service name. Can you point me in the right direction as to which file I should modify to fix the issues with the Flower pod?

**Comment by puckel** [comment]
Could you confirm that you're using docker-airflow and not kube-airflow ?

**Comment by stobias123** [comment]
I imported the docker-airflow compose file. I was able to resolve by setting an environment variable "FLOWER_PORT" to 5555. 

I'm pretty sure this issue is unique to open shift.

**Comment by emirot** [comment]
@stobias123 thanks ! I had the same issue on k8s with this image using aws.

**Comment by OriHoch** [comment]
thanks, solved it for me as well with k8s on GKE :+1:

**Comment by kevcampb** [comment]
The issue is that kubernetes (openshift) will define env variables based on the name of the service, so that the docker image can read them. 

```
airflow@flower-214658948-r56fm:~$ export
declare -x DEBIAN_FRONTEND="noninteractive"
declare -x EXECUTOR="Celery"
declare -x FLOWER_PORT_5555_TCP="tcp://10.0.0.11:5555"
declare -x FLOWER_PORT_5555_TCP_ADDR="10.0.0.11"
declare -x FLOWER_PORT_5555_TCP_PORT="5555"
declare -x FLOWER_PORT_5555_TCP_PROTO="tcp"
declare -x FLOWER_SERVICE_HOST="10.0.0.11"
declare -x FLOWER_SERVICE_PORT="5555"
declare -x FLOWER_SERVICE_PORT_5555="5555"
```

This conflicts with the FLOWER_PORT env variable which flower expects. Bizarrely flower allows an env var of 'FLOWER_PORT.*' to be supplied.

```
    flower/command.py:126
    def is_flower_envvar(self, name):
        return name.startswith(self.ENV_VAR_PREFIX) and\
               name[len(self.ENV_VAR_PREFIX):].lower() in default_options
```

setting an env var of FLOWER_PORT may solve this, but it seems fragile. It depends on the ordering of results returned by os.environ, which may or may not be deterministic - I'd have to study for that one.

I think the only comprehensive fix for this is either:
a) Raise a bug in celery and change the affected code to ignore FLOWER_PORT_5555_TCP et al
b) Rename the docker image to be flower2 or something similar
