### ISSUE TITLE
issue running LocalExecutor docker-compose file

### ISSUE THREAD

**Issue by riguy724** [puckel/docker-airflow#47]
Hey there,

Loving the docker setup you put together here, it's been very helpful in getting me closer to a production airflow configuration, and learn more about the components!

I am having some difficulty running the docker-compose-LocalExecutor.yml setup though, using docker v1.12.1 and running on osx.  I attached the docker-compose logs output here.  I tried this with the CeleryExecutor as well, and had some very similar results.  I tried removing the local volumes just to ensure I was in a clean environment, but things just don't seem to work :/

If you have any suggestions on how I might get things running (including the scheduler and web UI components for flower/airflow running) please let me know!

[airflow-logs.txt](https://github.com/puckel/docker-airflow/files/563356/airflow-logs.txt)

**Comment by puckel** [comment]
Could you please describe the problem and only extract your issue from de log (not the raw log file) ?
