### ISSUE TITLE
Update to Airflow 1.10.7

### ISSUE THREAD

**Issue by impredicative** [puckel/docker-airflow#481]
Airflow 1.10.7 has been released:
* https://github.com/apache/airflow/releases/tag/1.10.7
* https://pypi.org/project/apache-airflow/1.10.7/

**Comment by hyzhak** [comment]
@puckel what is the plan to get up-to-date version of AirFlow in Docker container?

**Comment by hyzhak** [comment]
btw I have tried to:
```bash
docker build --rm --build-arg AIRFLOW_VERSION=1.10.7 --no-cache -t puckel/docker-airflow:1.10.7 .
```
on current master branch and it works fine

**Comment by impredicative** [comment]
> btw I have tried to:
> 
> ```shell
> docker build --rm --build-arg AIRFLOW_VERSION=1.10.7 --no-cache -t puckel/docker-airflow:1.10.7 .
> ```
> 
> on current master branch and it works fine

Okay but a lot of other things can need updating, e.g. the config file.

**Comment by hyzhak** [comment]
Sure, but it is quick and dirty solution to get new up-to-date version of AirFlow

**Comment by impredicative** [comment]
This issue was evidently resolved by the repo owner, and so it is being closed.
