### ISSUE TITLE
README incorrect: Docker Pull then Build per the docs, doesn't work

### ISSUE THREAD

**Issue by yehoshuadimarsky** [puckel/docker-airflow#485]
I want to use some of the ARG arguments in the DockerFile when building it. Per the [README](https://github.com/puckel/docker-airflow#installation), this is what I should be doing.

<details>
  <summary>Instructions from the README</summary>

## Installation

Pull the image from the Docker repository.

    docker pull puckel/docker-airflow

## Build

Optionally install [Extra Airflow Packages](https://airflow.incubator.apache.org/installation.html#extra-package) and/or python dependencies at build time :

    docker build --rm --build-arg AIRFLOW_DEPS="datadog,dask" -t puckel/docker-airflow .
    docker build --rm --build-arg PYTHON_DEPS="flask_oauthlib>=0.9" -t puckel/docker-airflow .

or combined

    docker build --rm --build-arg AIRFLOW_DEPS="datadog,dask" --build-arg PYTHON_DEPS="flask_oauthlib>=0.9" -t puckel/docker-airflow .
</details>

But, this doesn't work for me. See output below. I'm clearly using the `docker build` command wrong somehow, I'm not sure how to use it with setting the `--build-arg` while using a binary image instead of a DockerFile. Can someone please assist? Thanks.

```
C:\Users\JoshDimarsky.AzureAD>docker pull puckel/docker-airflow
Using default tag: latest
latest: Pulling from puckel/docker-airflow
Digest: sha256:4751d7a7bfdbb0eb7b49fe54b6cae5769c65989fbcd5e79c0cbb5b6c9a7d80e7
Status: Image is up to date for puckel/docker-airflow:latest
docker.io/puckel/docker-airflow:latest

C:\Users\JoshDimarsky.AzureAD>docker build --rm --build-arg AIRFLOW_DEPS="datadog,dask" --build-arg PYTHON_DEPS="flask_oauthlib>=0.9" -t puckel/docker-airflow .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile C:\Users\JoshDimarsky.AzureAD\Dockerfile: The system cannot find the file specified.
```

**Comment by puckel** [comment]
clone the github repository and then run the build
