### ISSUE TITLE
Error when building an SSH connection to a remote Host

### ISSUE THREAD

**Issue by sdikby** [puckel/docker-airflow#50]
Hi, i got the following error when trying to load a new DAG(logs from the scheduler ):
`
[2016-11-16 10:44:39,687] {jobs.py:680} INFO - Starting the scheduler [2016-11-16 10:44:39,687] {models.py:154} INFO - Filling up the DagBag from /usr/local/airflow/dags [2016-11-16 10:44:39,794] {base_hook.py:53} INFO - Using connection to: 10.1.100.71 [2016-11-16 10:44:39,794] {models.py:250} ERROR - Failed to import: /usr/local/airflow/dags/osf_dag_v3.py Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/airflow/models.py", line 247, in process_file m = imp.load_source(mod_name, filepath) File "/usr/local/airflow/dags/osf_dag_v3.py", line 29, in <module> ssh_hook = SSHHook(conn_id='ssh_conn') File "/usr/local/lib/python2.7/dist-packages/airflow/contrib/hooks/ssh_hook.py", line 55, in\__init\__ self.key_file = conn.extra_dejson.get('key_file', None) File "/usr/local/lib/python2.7/dist-packages/airflow/models.py", line 590, in extra_dejson if self.extra: File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 293, in\__get\__ return self.descriptor.\__get\__(instance, owner) File "/usr/local/lib/python2.7/dist-packages/airflow/models.py", line 534, in get_extra return FERNET.decrypt(bytes(self._extra, 'utf-8')).decode() File "/usr/local/lib/python2.7/dist-packages/cryptography/fernet.py", line 103, in decrypt raise InvalidToken InvalidToken`

**Comment by puckel** [comment]
Hi,

With CeleryExecutor ?

**Comment by sdikby** [comment]
@puckel yes !

**Comment by puckel** [comment]
Did you've set the environment variable FERNET_KEY ?

>         environment:
>             # - LOAD_EX=n
>             # - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA

**Comment by sdikby** [comment]
i have set it only in the webserver,scheduler and the worker service

**Comment by puckel** [comment]
Can you confirm it's the same key in airflow.cfg for each container ?

**Comment by sdikby** [comment]
@puckel  you have a point here ! No  it is not the same,
Here is my docker file:

version: '2'
services:
    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=airflow
            - RABBITMQ_DEFAULT_PASS=airflow
            - RABBITMQ_DEFAULT_VHOST=airflow

    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - /stor/OSF_Tracking/tmp/postgresql:/var/lib/postgresql/data

    webserver:
        image: puckel/docker-airflow
        restart: always
        depends_on:
            - postgres
            - rabbitmq
        environment:
            # - LOAD_EX=n
            - EXECUTOR=Celery
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
        volumes:
            - /stor/OSF_Tracking/airflow_docker/dags_folder:/usr/local/airflow/dags
            - /stor/OSF_Tracking/airflow_docker/logs:/usr/local/airflow/logs
            - /stor/OSF_Tracking/airflow_docker/.ssh:/usr/local/airflow/.ssh
        ports:
            - "9595:9595"
        command: webserver

    flower:
        image: puckel/docker-airflow
        restart: always
        depends_on:
            - rabbitmq
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - /stor/OSF_Tracking/airflow_docker/dags_folder:/usr/local/airflow/dags
            - /stor/OSF_Tracking/airflow_docker/logs:/usr/local/airflow/logs
            - /stor/OSF_Tracking/airflow_docker/.ssh:/usr/local/airflow/.ssh
        environment:
            # - LOAD_EX=n
            - EXECUTOR=Celery
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
        command: scheduler -n 5

    worker:
        image: puckel/docker-airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - /stor/OSF_Tracking/airflow_docker/dags_folder:/usr/local/airflow/dags
            - /stor/OSF_Tracking/airflow_docker/logs:/usr/local/airflow/logs
            - /stor/OSF_Tracking/airflow_docker/.ssh:/usr/local/airflow/.ssh
        environment:
            - EXECUTOR=Celery
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
        command: worker

and the following is the fernet_key in each container:
Scheduler:
fernet_key = qtdVEfy3meGHSoHe7YsPoED5xY_lQUG6PWwkSZ70yaE=

Worker:
fernet_key = czEGU8lvxThAJ5JVVRm_NxD9S1_QhoiALYDthJubQg0=

Webserver:
fernet_key = 39XvKcNy16agkhw96c-Xc4YgRHa5xMqeREP0V764R8U=

**Comment by sdikby** [comment]
could the problem be with the entrypoint.sh ?

**Comment by puckel** [comment]
I check

**Comment by puckel** [comment]
So, I ran both docker-compose executor file and I've the good fernet_key inside each container (I've just pushed docker-compose file with fernet_key enabled)

**Comment by sdikby** [comment]
Do you have some some suggestions how do i fix this problem?

**Comment by puckel** [comment]
Could you try to ran my example file from last commit ?

**Comment by sdikby** [comment]
@puckel yes, i only have more volumes in my example but everything else is the same. Or should i rebuild the containers before ?

**Comment by puckel** [comment]
Which version are you using of docker & docker-compose ?

**Comment by sdikby** [comment]
@puckel fixed! but i don't know how. i deleted all the volumes, networks images and did this 
docker-compose -f docker-compose-CeleryExecutor.yml up -d
and i now it is fxed. Thank you

**Comment by puckel** [comment]
No problem. Thanks
