### ISSUE TITLE
airflow scheduler stuck

### ISSUE THREAD

**Issue by asnir** [puckel/docker-airflow#51]
Since the airflow version 1.7.1.3 the scheduler stuck probably due to a deadlock.
It seems like that setting the number of runs to 5 & auto restart didn't solve the problem.

possible solutions:

- Using older version of ariflow e.g. 1.6.2 
- Running `docker-compose restart scheduler` from time to time.

reference:
https://issues.apache.org/jira/browse/AIRFLOW-401

**Comment by darkk** [comment]
@asnir are you using LocalExecutor or CeleryExecutor? I have a workaround for CeleryExecutor that is limiting it's CPU time for the scheduler, so it's restarted as soon as it gets stuck in infinite loop:

It looks like an ugly hack, so I'm unsure if @puckel will welcome alike PR :-)

**Comment by asnir** [comment]
@darkk , i am using CeleryExecutor and i prefer to use an older version.

**Comment by puckel** [comment]
Hi,

Could you please try using the latest release (1.7.1.3-7) using redis insted of rabbitmq ?

Thanks

**Comment by IngoS11** [comment]
Hi guys,
with 1.7.1.3-7 I seem to have this or a similar problem. The Scheduler and Worker docker container continuously restart after about 30 seconds. This is with both configs LocalExecutor and CeleryExecutor.

**Comment by yuxiaorui** [comment]
using redis insted of rabbitmq cann't realy solver this problem,use supervisor in container to start airflow scheduler

**Comment by puckel** [comment]
Please check with the latest stable release 1.8.0.
