### ISSUE TITLE
[Question] Strange Problem with AWS and Redis

### ISSUE THREAD

**Issue by Teepot418** [puckel/docker-airflow#539]
Hello everybody,

I have a strange problem concerning the airflow worker, redis and the celery executer. I'm trying to deploy Airflow to AWS ECS with the webserver, scheduler and worker in different containers. The webserver and scheduler are working fine, but I cannot start the worker. (In my local docker environment it's working fine). As image I use puckel/airflow with some smaller changes, which shouldn't be the cause for this issue.

It would be great if somebody with greater knowledge of Airflow can take a look at my stackoverflow post. I really don't know whats going on. 

[Stackoverflow Post](https://stackoverflow.com/questions/61211671/airflow-worker-not-starting-with-celery)

Thanks in advance for your help!

**Comment by wittfabian** [comment]
This question has already been answered on Stackoverflow.
