### ISSUE TITLE
Issues with ENV variables using docker-compose

### ISSUE THREAD

**Issue by Schachte** [puckel/docker-airflow#548]
I'm directly cloning the repo and spin up the containers matching the celery compose file. When I check the cfg file, it just shows the defaults for SequentialExecutor, things aren't getting interpolated either, such as the postgres env values. 

Why is this happening? 

`executor = SequentialExecutor`

**Comment by wittfabian** [comment]
Settings that are set via environment variables are not stored in the config file.

You can view the settings in the UI (Admin > Configuration).

![Unbenannt2](https://user-images.githubusercontent.com/8940922/80942128-51a43f80-8de4-11ea-87cc-9116aadbd25d.PNG)

**Comment by gundoganalperen** [comment]
Although I use Celery via `docker-compose -f docker-compose-CeleryExecutor.yml up -d`, I still see that the executor is set to `SequentialExecutor`.

**Comment by wittfabian** [comment]
Where do you see that?
Can you show a picture of it?
