### ISSUE TITLE
Values of Airflow variables disappear on docker restart

### ISSUE THREAD

**Issue by Raccooneer** [puckel/docker-airflow#549]
Hi, 

the values of the Airflow Variables disappear, when I have to restart docker. The key, however, remains existent. As you can see in this first picture, I stored the variables (the visibility of a value from a key that includes the word "key" is a side issue... in my experience this should not happen as well). This issue became apparent, since I had to restart the computer and subsequently the docker image.

![image](https://user-images.githubusercontent.com/64844600/81066234-176a9900-8edd-11ea-9dfb-beb77d03abbf.png)

When I stop docker and restart it, the value is shown as "invalid" and editing it shows that there is no value stored anymore.

![image](https://user-images.githubusercontent.com/64844600/81066397-526ccc80-8edd-11ea-997b-9abd6ddfeb9a.png)

Some words on specs
docker-image
- puckel/docker-airflow:1.10.9
- postgres:9.6
- I used the docker-compose-LocalExecutor.yml to compose (I did add another mounted volume)

Docker
-  docker desktop (for windows) 2.2.0.5

Apart from this issue, DAGs run as expected.

Thanks and best 

Additional Note:
This issues is the same for manually entered key-value pairs and imported key-value pairs. It is also the same for single values and dictionairies.

**Comment by wittfabian** [comment]
I think your restart generates a new fernt-key. So the old values get invalid.

**Comment by Raccooneer** [comment]
Do you have an idea, how I could surpress this behavior?

**Comment by wittfabian** [comment]
You can set the environment variable directly in docker-compose file.

**Comment by Raccooneer** [comment]
> I think your restart generates a new fernt-key. So the old values get invalid.

This was correct...

> You can set the environment variable directly in docker-compose file.

This worked... (for anyone that may have the same issue, an example for this can be found  #275 )

Thus, I big THANK YOU to you!!!!

Variables with the word "key" in the name are still shown clearly... do you happen to have any idea on this issues as well?

**Comment by wittfabian** [comment]
Interesting... I will check this.

**Comment by wittfabian** [comment]
> Variables with the word "key" in the name are still shown clearly... do you happen to have any idea on this issues as well?

Is the status displayed as encrypted?

**Comment by Raccooneer** [comment]
> > Variables with the word "key" in the name are still shown clearly... do you happen to have any idea on this issues as well?
> 
> Is the status displayed as encrypted?

yes, indeed, it is...

**Comment by wittfabian** [comment]
With me, all veriables are encrypted, regardless of name.

**Comment by Raccooneer** [comment]
> With me, all veriables are encrypted, regardless of name.

Well, yes, the same for me. The issue is the visibility of keys and passwords. I expect variables with "password" or "key" in the name not to be previewed in clear text but to be shown as ***** in the varible overview... and in the edit view as well.

It was just a long shot to connect these issues... if you think, they are not related, I could open a new issue...!? Thanks so far.

**Comment by Raccooneer** [comment]
Apparently, the behavior has changed and "_key" suffix is not further supported for masking variables. However, "_apikey" still is as I have successfully tested. Thus, the masking works as expected... kinda.

That resolves all my issues. Thanks everyone!
