### ISSUE TITLE
Why is the container of the scheduler always restarting instead of using the official scheduler script?

### ISSUE THREAD

**Issue by james-woods** [puckel/docker-airflow#55]
I am currently looking into porting docker-airflow onto Kubernetes and I looked through the work of [kube-airflow](https://github.com/mumoshu/kube-airflow). One thing that puzzled me is that the exit of the scheduler makes Kubernetes think it crashed and gets into a `CrashLoopBackOff`. 
An alternative would be to run [airflow_scheduler_autorestart.sh](https://github.com/apache/incubator-airflow/blob/ff45d8f2218a8da9328161aa66d004c3db3b367e/airflow/bin/airflow_scheduler_autorestart.sh) instead. Is there a reason why this script is not used in the docker container for the scheduler?

**Comment by james-woods** [comment]
``` sh
#!/usr/bin/env bash
while echo "Running"; do
    airflow scheduler -n 5
    exitcode=$?
    if [ $exitcode -ne 0 ]; then
      echo "ERROR: Scheduler exited with exit code $?."
      exit $exitcode
      date
    fi
    sleep 30
done
```

This is something I came up with / I was thinking about.

**Comment by puckel** [comment]
Hi,

I'm using the recommendation read on airflow mainling-list indicated by mistercrunch. I'm only supporting docker for the moment, but you can make me a PR and I'll check this.
