### ISSUE TITLE
Permission denied for entrypoint.sh

### ISSUE THREAD

**Issue by christianto88** [puckel/docker-airflow#555]
I am trying to add PYTHON_DEPS and based on the README files we need to rebuild the docker image. After rebuild, the container cannot start and gives error
![image](https://user-images.githubusercontent.com/28486790/82559464-e0ada780-9b99-11ea-8a11-60264dccccbd.png)

**Comment by wittfabian** [comment]
On which operating system is the image built?

**Comment by wittfabian** [comment]
You can add `RUN chmod +x /entrypoint.sh`.

![grafik](https://user-images.githubusercontent.com/8940922/82643172-60c22480-9c0f-11ea-96f7-2f63d2191370.png)
