### ISSUE TITLE
built container not running

### ISSUE THREAD

**Issue by lzhou519** [puckel/docker-airflow#557]
So I'm new to docker and airflow so bare with me. 
I pulled all files of this repo and I built it using "docker build --rm -t airflow-image ." For some reason the image appears as <none>. So I tag the image with "docker image tag bf68b791d02b airflow-image". Then I run it using "docker run -d -p 8080:8080 airflow-image" and it seems to run but when I type "docker ps" I get nothing I also get nothing when I do to "http://localhost:8080/admin/".

Any one have this issue? And how did you resolve it? I attached an image of my commands and what I see in command prompt. Thanks. 

![docker_issues](https://user-images.githubusercontent.com/28630416/83218466-f09a2e00-a13b-11ea-93cd-febb487142aa.png)

**Comment by wittfabian** [comment]
Are you sure the image was built right?

You can list all Container with `docker ps -a`

You can show the logs with `docker logs <Container-ID>`

**Comment by lzhou519** [comment]
So I see that when I use "docker ps -a" I get that the airflow-image was exited immediately when I tried to run it. 
Also when I use docker logs <Container-ID> on the offending container I get no responses. 

The way I build it is to go to the local files that contain all the files from this repo then type "docker build --rm -t airflow-image ." I want to build it this way because I want to adjust the .cfg file. 

Am I building it correctly? Any help is appreciated. Thanks.

**Comment by wittfabian** [comment]
On which operating system is the image built?

Can you show the log of the build?

**Comment by lzhou519** [comment]
I'm doing this on windows with docker desktop and docker compose installed. 

How do I show the log of the build? Is it with docker logs <Container-ID>? I attached an image of me using those commands. Thanks. 
![docker_issues2](https://user-images.githubusercontent.com/28630416/83272398-173a8200-a199-11ea-8d62-d7675bbe590b.png)

**Comment by wittfabian** [comment]
Run the build command and copy the output

**Comment by wittfabian** [comment]
You can try to run the container without "-d" t see the logs.

**Comment by lzhou519** [comment]
I attached my output when I build the image. I added "&& apt-get install vim \" to the dockerfile to install an editor. In the build logs I get this below could that be the issue? 

The following additional packages will be installed:
  libgpm2 vim-common vim-runtime xxd
Suggested packages:
  gpm ctags vim-doc vim-scripts
The following NEW packages will be installed:
  libgpm2 vim vim-common vim-runtime xxd
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 7425 kB of archives.
After this operation, 33.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.

[docker_issues_build_logs.txt](https://github.com/puckel/docker-airflow/files/4702691/docker_issues_build_logs.txt)

Thanks!

**Comment by wittfabian** [comment]
Thats the problem.
You have to set the flags "-yqq" to confirm the installation.

See: https://github.com/puckel/docker-airflow/blob/master/Dockerfile#L43

**Comment by lzhou519** [comment]
ah. Thanks!
