### ISSUE TITLE
How to install jupyter on airflow

### ISSUE THREAD

**Issue by Raccooneer** [puckel/docker-airflow#562]
Hi,

I'm trying to install the jupyter notebook app on airflow. My goal is to `nbconvert` a notebook as part of a DAG. For this purpose, I wanted to use a `BashOperator()` to `cd` to the `mynotebook.ipynb` file directory and `jupyter nbconvert mynotebook.ipynb --to latex`. Hence, I tried to install jupyter but had no success and would be very thankful for help.

Observed behavior:

- Running either of the below results, basically in the error below:
  -  `jupyter nbconvert mynotebook.ipynb`  
  - `python jupyter nbconvert mynotebook.ipynb`, 
  - `python -c jupyter nbconvert mynotebook.ipynb`):

```/bin/sh: 1: juypter: not found```

Expected behavior:

- notebook gets converted

Steps to recreate

- The CLI was used to `pip install jupyter`, which was declared successfull
- `cd` to get to the file
- the command(s) described above

Best and thanks

PS: I will eventually require latex on the container for this one... If this is comparably destined to fail, please let me know. I would appreciate any help on the latex install as well. :)

**Comment by wittfabian** [comment]
Try it without "python".
Just "jupyter ...".

**Comment by Raccooneer** [comment]
Thanks for your input.

I guess my initial description was unclear. I changed it. I was actually trying what you proposed. I'm somewhat on the idea, that jupyter has not been put on the PATH but I'm still trying to figure that out

I appreciate your help

**Comment by Raccooneer** [comment]
Well, I guess it has something to do with this warning when installing jupyter

```
airflow@116d815f2039:/usr/bin$ pip install jupyter
Defaulting to user installation because normal site-packages is not writeable
```

I got a step closer so far: When I run just run `jupyter` in the conda shell, I get:
```
> jupyter
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]
jupyter: error: one of the arguments --version subcommand --config-dir --data-dir --runtime-dir --paths is required
```
and now I can achieve the same when running the follwoing command, which basically points directly to the `.py` file of jupyter:
```
$ python /usr/local/airflow/.local/lib/python3.7/site-packages/jupyter.py 
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json]
                  [subcommand]
```

However, this one cannot connect to `nbconvert`. (yes, I have tried to use the absolute path to the nbconvert folder or `nbconverapp.py` as well)

```
$ python /usr/local/airflow/.local/lib/python3.7/site-packages/jupyter.py nbconvert mynotebook.ipynb --to html
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/jupyter.py", line 10, in <module>
    run_module('jupyter_core')
  File "/usr/local/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/jupyter_core/__main__.py", line 3, in <module>
    main()
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/jupyter_core/command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-nbconvert` not found.
```

I have tried to run the `nbconvertapp.py` directly like the `jupyter.py` above, but that produced:
```
$ python /usr/local/airflow/.local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py  mynotebook.ipynb --to html
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 28, in <module>
    from .exporters.base import get_export_names, get_exporter
ImportError: attempted relative import with no known parent package
```

So, eventually my impression is, that
- neither jupyter nor nbconvert are installed as they should be on the container. And I'm not completely sure yet, how to put either on the PATH, or confident, that this would help. 

My goal would rather be to do all of this with the docker-compose file. So, if somebody has an idea of solving the *on the fly install* problem by including another image or some lines in the Dockerfile, that would greatly help as well.

Thanks!!!

**Comment by pektinasen** [comment]
Go to your Dockerfile and add `pip3 install jupyter` to the RUN layer.
Or for testing do `docker-compose exec -u root ...` when accessing the container. 

This has to do with PATH and permissions because you installed jupyter as airflow user and not as root.

**Comment by Raccooneer** [comment]
Your suggestion actually brought me to a running solution... for whatever reason, any `docker-compose up` execution (on a running container, after stopping the container or deleting the container entirely) does not implement the changes I make to the Dockerfile. So adding the `pip3 install jupyter` on the RUN layer changed nothing (I tried to add it to a piped RUN command and individually... nothing worked). I had the same issue with installing R packages via dockerfile. Has no effect without any error thrown... an issue for another time.

However, with `docker-compose exec -u root ...` way worked such that I was able to install all nessecary packages to get this thing running (which actually meant several expected and unexpected packages):
```
$ docker-compose exec -u root webserver pip install jupyter
$ docker-compose exec -u root webserver pip install matplotlib
$ docker-compose exec -u root webserver pip install seaborn
$ docker-compose exec -u root webserver apt-get update
$ docker-compose exec -u root webserver apt-get install -y inkscape
$ docker-compose exec -u root webserver apt-get install -y pandoc
$ docker-compose exec -u root webserver apt-get install -y texlive-xetex
```
I could have piped these commands with `&&` but apparently you have to put everything in quotes for that and that kind of didn't work for me.

Thanks a lot.

EDIT:
of course, I built it wrong... with `docker-compose build` and the following run layer in the dockerfile, it works. More complex notebooks eventually revealed, that seaborn, matplotlib and all the other fun stuff to create a nice report are missing as well.

```
RUN apt-get update && \
    apt-get install -y inkscape && \
    apt-get install -y -y pandoc && \
    apt-get install -y texlive-xetex && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --upgrade pip && \
    pip3 install jupyter && \
    pip3 install xlrd && \
    pip3 install openpyxl && \
    pip3 install matplotlib && \
    pip3 install seaborn
```

The same way I got R installed with packages on docker. :)

So, I guess I can close this now
