### ISSUE TITLE
Very large Airflow Logs!

### ISSUE THREAD

**Issue by sdikby** [puckel/docker-airflow#57]
Hi,

how come that Airlow can generate 140 GB Logs under /stor/OSF_Tracking/docker/overlay2/d90dc3c63c3849bef95d82a47e67c138b54db7316860252a75ca308351cd00fe/diff/usr/local/airflow/logs ?

My other questions are is there a way to suppres that? or make like log rotation?
How to put those logs as a volume in docker ?
Any suggestion is very much appreciated

**Comment by puckel** [comment]
Hi,

You can use a volume :

>         volumes:
>             - /localpath/to/logs:/usr/local/airflow/logs

or you can store logs remotely in AWS S3 or Google Cloud Storage (ie airflow.cfg).
