### ISSUE TITLE
Allow alternate location for requirements.txt

### ISSUE THREAD

**Issue by stevenpitts** [puckel/docker-airflow#591]
[Currently](https://github.com/puckel/docker-airflow#install-custom-python-package), if we want to have a `requirements.txt` installed, we need to put it at `/requirements.txt`. However, for some services like AWS ECS, [we can't mount a file](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_MountPoint.html), we can only mount a volume (as a directory) at a given location.

This makes it difficult to put the `requirements.txt` at `/requirements.txt`; it suggests that we need to mount the volume at `/`, and put `requirements.txt` in that volume, but mounting the volume at `/` wouldn't make sense.

Could we have an alternate allowed location for `requirements.txt`, such as `/requirements/requirements.txt`, and have a check that if `/requirements.txt` doesn't exist but `/requirements/requirements.txt` does, we copy the file from `/requirements/requirements.txt` to `/requirements.txt`?

**Comment by stevenpitts** [comment]
This is also relevant to just docker-compose. For example:
Let's say the `requirements.txt` isn't a file on my host machine, it's a file in a Github repo. I decide to use a oneoff container to grab that file from the github repo, and add it to a shared volume. Since the file isn't on my host machine, I can't just have a "shared file", it needs to be a shared volume.
The mount point on my `pull_requirements_file_from_repo` container can be whatever, since all I have to do is copy the file from the web to a file in that volume. But there's still the issue of where to mount the volume on the Airflow container; we'd have to mount it at `/` to make the file appear at `/requirements.txt`, which makes no sense.

**Comment by jakubberezowski** [comment]
Hi @makusu2,
if you use AWS ECS on EC2 it should not be a problem with mounting the `requirements.txt` as a file. This is working for me, like this:
```
resource "aws_ecs_task_definition" "worker" {
   ...
  volume {
    name      = "requirements_on_ec2"
    host_path = "/home/ec2-user/airflow/docker/requirements.txt"
  }
  ...  
```
and the task definition:
```
 "mountPoints": [
      ...
      {
        "readOnly": true,
        "containerPath": "/requirements.txt",
        "sourceVolume": "requirements_on_ec2"
      },
      ...
    ],
```
The problem occurs if you want run the docker on Fargate, and then you would use probably AWS EFS for mounting the `requirements.txt`. In this case it creates a directory.

How have you solved this issue?

**Comment by stevenpitts** [comment]
Sorry I never replied to this, I don't know how I missed it; I'm actually not working on the relevant project anymore, so I can't test your suggestion. Thank you for the response, though!
