### ISSUE TITLE
Can't access webserver

### ISSUE THREAD

**Issue by sdikby** [puckel/docker-airflow#60]
i can't acces the webserver.
i have though noticed that the webserver port don't propagate correctly
![screenshot from 2017-01-17 15 32 39](https://cloud.githubusercontent.com/assets/12047164/22024483/70fab6f8-dcca-11e6-9b3f-7463db8f1415.png)

I have attached a screenshot from docker ps -a

**Comment by sdikby** [comment]
@puckel, i have fixed the problem by using the  1.7.1.3-3 version. I also used the same version with adding manually all the changes between  1.7.1.3-3 and 1.7.1.3-6 #52 #39 but without the "Make entrypoint.sh root-owned " pull request(i didn't test it). I bumped up rabbitmq version to 3.6.6-management and posgresql to 9.6.1. I also pinned jinja2 to 2.8.1 in the docker file like suggested in airflow repo.

I don't know exactly how it work when building a new docker container for airflow but i think that some new commits in the airflow incubator between 1.7.1.3-3 and 1.7.1.3-6 caused the problem.

For that i suggest to start using travis-ci. Because there is a lot of dependencies and one cannot test all that manually. What do you think ?

**Comment by puckel** [comment]
Hi,

Could you please try using the latest release (1.7.1.3-7) ?

Thanks

**Comment by jgerardsimcock** [comment]
I am having a similar problem as this. Is there a workaround to propagate the port?

**Comment by puckel** [comment]
First, check that nothing is already listening on you host tcp/8080 (`netstat -ptnl`)
Then, copy/past me the result of `docker ps` and `netstat -ptnl` and `iptables -n -L -v`

**Comment by jgerardsimcock** [comment]
I ran `docker ps` than ran `docker kill <pid>` to make sure everything was clean. Then after running `docker-compose -f docker-compose-CeleryExecutor.yml up -d` here is what my connections look like:
<img width="1241" alt="screen shot 2017-02-21 at 9 24 46 am" src="https://cloud.githubusercontent.com/assets/6101444/23176409/a463704e-f817-11e6-86d2-6f688e23bef9.png">


Here is a link to my docker file (https://github.com/ClimateImpactLab/docker-airflow/blob/master/Dockerfile)

**Comment by puckel** [comment]
Hi,

I've fixed the problem in branch v1.8.0 (commit d4636f9). Airflow try to fetch logs on port tcp/8793 which is created by airflow worker. If using LocalExecutor, the sheduler and the webserver must be on the same host.

**Comment by puckel** [comment]
Despite the NAME of your dockerairflow_webserver_1, nothing seems weird.
Could you please past the result of `curl -IL http://$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dockerairflow_webserver_1):8080/admin`

**Comment by jgerardsimcock** [comment]
Sorry for the delay. I was away for a bit. 
![screen shot 2017-03-07 at 14 34 04](https://cloud.githubusercontent.com/assets/6101444/23681265/3a7ca6c8-0343-11e7-9a87-26664fabbca6.png)

**Comment by puckel** [comment]
Hmm weird, because you've a 200 OK, so it seems it's working. Which error you have in your browser ?

**Comment by jgerardsimcock** [comment]
I should note that I am running docker an EC2 instance and want to forward the port to my local machine.  Perhaps I am missing a step?

**Comment by mendhak** [comment]
Ah so you should browse to your server then

`http://ec2-instance-ip-address:8080`

If you're trying to browse to `http://localhost:8080` on your own desktop then nothing will work since nothing is listening locally.

If you want a local 8080 to actually 'go' to that EC2 instance's 8080, then you're probably looking for [SSH tunneling](http://blog.trackets.com/2014/05/17/ssh-tunnel-local-and-remote-port-forwarding-explained-with-examples.html)
