### ISSUE TITLE
How to install custom python package without restarting?

### ISSUE THREAD

**Issue by ericng-tx** [puckel/docker-airflow#603]
I am using docker compose to run airflow `docker-compose -f docker-compose-CeleryExecutor.yml up -d`, when I install new package I would edit `requirements.txt` as suggested in [https://github.com/puckel/docker-airflow#install-custom-python-package](https://github.com/puckel/docker-airflow#install-custom-python-package), and `docker-compose -f docker-compose-CeleryExecutor.yml down` and then up again.

Is there a way to avoid the down time? Sorry if the question is too ignorant...

**Comment by roveo** [comment]
`docker-compose exec  -u root webserver bash`, then `pip install -r /requirements.txt`

**Comment by ericng-tx** [comment]
> `docker-compose exec -u root webserver bash`, then `pip install /requirements.txt`

Thanks a lot! For me `docker-compose exec -u root worker bash` and then `pip install -r /requirements.txt` worked.

**Comment by roveo** [comment]
> `pip install -r /requirements.txt` worked.

Yes, sorry, forgot the `-r`, edited the original answer.
