### ISSUE TITLE
SSH from docker container to other VMs

### ISSUE THREAD

**Issue by sj860908** [puckel/docker-airflow#61]
Hello, 
I have a airflow check that performs BashOperator with below command.
``` ssh root@xxxxx python2.7 xxx.py ```

Task failed so I went in to the worker container and checked that `ssh` is missing in container.
I can't find online how to install ssh on docker container. If there is anything you can help, very much appreciated.

**Comment by sdikby** [comment]
Hi @sj860908 ,
i have tried to install `openssh-client` by doing this in the docker file `&& pip install openssh-client` and the logs on the console showed that it has been installed successfully. But when i got into the Airflow worker cli with docker exec i didn't find it.
So as a workaround i did this:
`sudo docker exec -u root -it container_num /bin/bash`
`apt-get update`
`apt-get install openssh-client`

**Comment by puckel** [comment]
Hi,
You've to rebuild the docker image with openssh. You've to add remote host to `known_hosts` too (ie https://github.com/puckel/docker-airflow/issues/38#issuecomment-273355115)
