### ISSUE TITLE
Question on updating DAGs in compose

### ISSUE THREAD

**Issue by astewart-twist** [puckel/docker-airflow#64]
This is really cool, thanks for putting it together.  What in your view would be the best way to update DAGs in the context of this deployment?    Would you suggest just forking this repo and updating the whole docker-compose deployment every time one needs to update a DAG, or possibly placing the DAGs in a container volume mounted in the Airflow containers?

**Comment by puckel** [comment]
Hi,
I don't think I'm the right person to answer. Maybe you can try on the mailing list (http://mail-archives.apache.org/mod_mbox/incubator-airflow-dev/)

**Comment by astewart-twist** [comment]
Sure.  I was just seeing if you had any opinion on it.  Thanks!

**Comment by bryan3189** [comment]
@astewart-twist Checking to see if you found a way to update dags in a running airflow container without restarting the container. 

@puckel  is there a way to have a remote dags folder that airflow can point to? In this way the remote location can be updated with new Dags and airflow container can pull new changes.

**Comment by astewart-twist** [comment]
@bryan3189 I've come up with a couple ideas with some colleagues, only tried a few:

1) create a separate volume container for the dags/plugins and mount it into the other containers.  On a multi-host deployment that might also require some kind of NFS or fancy docker volume plugin solution.  

2) use a cron job or even a DAG to pull dags from a git repo

3) use a cron job or even a DAG to pull dags from S3 (or similar)

4) write an airflow plugin to directly load DAGs into the database

**Comment by KimchaC** [comment]
On the host I have a GIT repo with the following folder structure:
```
localhost:etl Kim$ tree
.
├── Docker
│   ├── Dockerfile
│   ├── Makefile
│   ├── docker-compose.yml
├── airflow
│   ├── dags
│   │   ├── ...
│   ├── plugins
│   │   ├── ...
```

In my docker-compose I include the airflow folders as volumes:
```
        volumes:
            - ../airflow/dags:/usr/local/airflow/dags:z
            - ../airflow/plugins:/usr/local/airflow/plugins:z
```

Whenever I update my DAGs or plugins I just pull the changes on the host in GIT. They immediately become available in airflow.

When a task is executed it launches a new process, which loads the latest DAGs and code. The web interface has a refresh DAG button and the scheduler reloads the DAGs and plugins on a regular interval.

**Comment by zhongjiajie** [comment]
I use Pycharm's `Tools -> Deployment` to connect local DAG and other file like `sql`, when I finish DAG define, I use to Pycharm `Upload to remote` buttom upload local file to server. For that I could test DAG immediately and it could reflush the DAG BTW.

But it don't work with plugins.

**Comment by bryan3189** [comment]
Awesome that's super helpful. Thank you @astewart-twist @KimchaC @zhongjiajie
