### ISSUE TITLE
passwords aren't encrypted when using celery compose

### ISSUE THREAD

**Issue by r-richmond** [puckel/docker-airflow#67]
Not sure whats going on here but after doing the following steps I can't seem to have the passwords in connections encrypted.

```
git clone https://github.com/puckel/docker-airflow.git
docker-compose -f docker-compose-CeleryExecutor.yml up -d
# check http://localhost:8080/admin/connection/
# nothing is encrypted
```

My understanding is that these should all be encrypted as 

1. there is a valid fernet_key in place. 
1. We've installed the crypto package

I've tried changing the fernet key but that doesn't seem to work either.

whats really strange is that if I don't use the celery compose and instead just run it the connections are encrypted. Any ideas whats going on?

Relevant Resource?
https://airflow.incubator.apache.org/faq.html#why-are-connection-passwords-still-not-encrypted-in-the-metadata-db-after-i-installed-airflow-crypto

![screen shot 2017-02-26 at 5 09 51 pm](https://cloud.githubusercontent.com/assets/9246654/23345639/6d43dd28-fc46-11e6-8d45-6c83e384fe0e.png)

**Comment by puckel** [comment]
Hi,
I've check 1.7.1.3-7 and 1.8.0rc4 (branch v1.8.0), with the current fernet_key in example in .yml files it doesn't work, I regenerated a new key `46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho` and it works correctly, but you need to follow the documentation `you need to open each connection in the connection admin UI, re-type the password, and save it`

![Image of airflow](http://pix.toile-libre.org/upload/original/1488189946.png)
