### ISSUE TITLE
ldap failing

### ISSUE THREAD

**Issue by sj860908** [puckel/docker-airflow#70]
Hello, I had no problem setting up ldap authentication before,
and after couple modification to the code, I am no longer able to bind ldap connection with webserver showing `AuthenticationError: Cannot bind to ldap server`.

I am able to telnet from the container, so I know this isnt the network problem..
If I can get any help or way to debug this, it would be really really helpful since I've been stuck with this for couple days now.

Thanks in advance for any help.

**Comment by alexthehurst** [comment]
@sj860908
Did you find a resolution to the ldap issue?
