### ISSUE TITLE
docker-compose issue

### ISSUE THREAD

**Issue by ToGoBananas** [puckel/docker-airflow#72]
I have tried to run docker-compose -f docker-compose-CeleryExecutor.yml up -d

But recieved errors
ERROR: for webserver  No such image: sha256:3631d65918560df72f335194d391370a09ea944ab9f7a9f225611829bd883bdf

ERROR: for flower  No such image: sha256:3631d65918560df72f335194d391370a09ea944ab9f7a9f225611829bd883bdf

**Comment by puckel** [comment]
Yes, you've to update the git repository.
Airflow bump to rc5.
