### ISSUE TITLE
Running other CLI arguments?

### ISSUE THREAD

**Issue by cameres** [puckel/docker-airflow#89]
Is there any prescribed way to run other command line arguments w/ airflow like `airflow test` for testing a particular task or is this docker image & compose file made w/ the intention of only running the scheduler? I've been playing around with connecting to a container & running tests in the following manner...

```shell
docker exec -i -t <container> /bin/bash 
airflow test ...
```

**Comment by puckel** [comment]
Hi @cameres 
Check the [entrypoint.sh](https://github.com/puckel/docker-airflow/blob/master/script/entrypoint.sh) I think you can add an exception (like `version`) for `airflow test`
I need to find time to rewrite the entrypoint.sh but feel free to make a PR.
