### ISSUE TITLE
https redirect issue behind ALB

### ISSUE THREAD

**Issue by flynnCoolblue** [puckel/docker-airflow#99]
Having an issue running this on AWS (ECS) behind an ALB. Issue sounds just like this one: https://github.com/ApacheInfra/superset/issues/978

Has anyone hit an issue when running this behind ALB running https? Is there some config we can add into the config file to allow https redirects?

**Comment by rdtr** [comment]
I'm trying to setup ELB -> nginx -> airflow web (SSL is terminated by ELB) and hit the issue.
I think this issue is related
https://github.com/apache/incubator-airflow/pull/1869
But it looks blocked by gunicorn update and got stuck for a while...

**Comment by Jie-Yang** [comment]
I am having a similar problem: 
Have you found the solution yet? 

I have tried:
set ENABLE_PROXY_FIX = True in superset_config, 
and set FORWARDED_ALLOW_IPS=* as Environment variable, but not luck. 

FYI, my Gunicon version is 19.7.1, superset is 0.18.5.

Thanks
Jay

**Comment by Jie-Yang** [comment]
For people may come across the same problem, I have found the problem. By mistake, I set protocol of target group to HTTPS. When I change it to HTTP, everything works!

**Comment by rdtr** [comment]
@Jie-Yang Do you mean you can access airflow web via HTTPS?
In my company HTTPS is basically must, so I don't want to use HTTP for web UI external access...

**Comment by Jie-Yang** [comment]
@rdtr 
The problem I had is from Apache Superset. But since both of us come to the same forum here, Superset and Airflow seems based on the same tech stack: flask, FAB, etc. 

Anyway, my superset sits in AWS ECS, and all HTTPS is configured on AWS ELB.

**Comment by florian0410** [comment]
> I am having a similar problem:
> Have you found the solution yet?
> 
> I have tried:
> set ENABLE_PROXY_FIX = True in superset_config,

I was encountering the same issue using tag 1.2.0 from this repository.

I think that using **ENABLE_PROXY_FIX** is the solution but you does not seem to declare it well.

I fixed it using the proxy fix variable in my docker-compose file as follow:
```yaml
- AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=true
```
Work fine and I'm happy now :+1:

**Comment by pjroth** [comment]
See https://airflow.apache.org/howto/run-behind-proxy.html for official docs.
